default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: blog_dev
  username: root
  password: root
  host: localhost
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: myblog
